### ISSUE TITLE
MySQL Exception

### ISSUE THREAD

**Issue by LightningDesign** [weihao/EnchantmentsEnhance#142]
The plugin is successfully conected to database. But i think you made a mistake in your Code. If i change the server, the data will not be saved.

all i got is this sql Exception
https://hastebin.com/kuzunajixe.sql
http://prntscr.com/o7idou

`[17:12:03] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`playername` = 'LightningDesign'' at line 1

**Comment by lgou2w** [comment]
Detailed stack trace dump? And MySQL version?

**Comment by LightningDesign** [comment]
Stack trace dump not yet at the moment. But here my sql versions. btw i have over 20 Plugins, that works current with my Database, so i think the problem is not on my side.

https://prnt.sc/o9amsp
and here are the plugins that are currently running:
http://prntscr.com/o9ao5y

i programm with mysql too, so i think the problem is in your sql prepared statements ...

**Comment by lgou2w** [comment]
According to the stack information, the problem should be here: Line 102

https://github.com/25/EnchantmentsEnhance/blob/400f88d91ca30803a05a7c08da7b3ea0c94b2f25/EnchantmentsEnhance-Plugin/src/main/java/org/pixeltime/enchantmentsenhance/mysql/DataStorage.java#L87-L116

But i tested this StringBuilder spliced SQL with no syntax error:

> UPDATE \`enchantmentsenhance\` SET \`failstack\` = ?, \`items\` = ?, \`valks\` = ?, \`grind\` = ?WHERE \`playername\` = ?;

@25 Need help

**Comment by LightningDesign** [comment]
Mybe use `queryBuilder.append("WHERE 'playername' = ?;");` I mean the " ' " on this part...

**Comment by LightningDesign** [comment]
I prefer this method:

`public static void update(String qry) {
		if(isConnected()) {
			try {
				con.createStatement().execute(qry);
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
	}`


`public static void updateDiamond(String uuid, Long diamondAmount, String typ) {
		
		if(!master.isConnected()) {
			master.connect();
		}
		
		master.update("UPDATE CounterOres SET " + typ + "='"+diamondAmount+"' WHERE uuid='"+uuid+"'");
	}`

**Comment by LightningDesign** [comment]
i prefer this method for table updates.

Updater methode:
https://hastebin.com/idegavegur.cpp

get the new data:
https://hastebin.com/denasozepu.cpp

**Comment by 25** [comment]
@LightningDesign Link is dead. Could you paste the code here on GitHub?

**Comment by weihao** [comment]
Solved!

Please use the latest release.
