### ISSUE TITLE
SkillAPI integration

### ISSUE THREAD

**Issue by weihao** [weihao/EnchantmentsEnhance#173]
`LordRamma`: Conflict with the SkillAPI plugin. Players' lives return to normal (20 hearts) when using healing spells. Ex: Pirophagia

**Comment by 25** [comment]
Ref: https://github.com/Eniripsa96/EnchantmentPack/blob/845cf970975f7a02cbcae4bc3343b2f502bfa406/src/com/sucy/enchant/passive/Life.java

**Comment by weihao** [comment]
I realized that this is caused by the hardcoded value. After the fix, the plugin should be compatible with SkillAPI.
