### ISSUE TITLE
MySQL data sync error

### ISSUE THREAD

**Issue by Soldier233** [weihao/EnchantmentsEnhance#188]
### What behaviour is observed:
the plugin using mysql mode will lose data when changing server
### Steps to reproduce:
Connect two servers of EE to one mysql table
change server, data lose sometime.

### Plugin list:
```[23:25:49 INFO]: Plugins (32): AdvancedCleaner, Citizens, CMI, CommandNPC, Craftconomy3, DiamondLand, DiamondWorld, EnchantmentsEnhance, LockettePro, mcMMO, MiaoBoard, Multiverse-Core, Multiverse-NetherPortals, MyPet, PermissionsEx, PlaceholderAPI, PlayerPoints, PlayerSQL, PlugMan, ProtocolLib, QuickShop, RandomParachute, Residence, SimpleORM, SQLibrary, TAB, TrChat, TrMenu, Vault, ViaVersion, VipSystem, WorldEdit```
### Enchantments Enhance build number:
```This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT
[23:26:48 INFO]: EnchantmentsEnhance version 7.9.7
[23:26:48 INFO]: This is a Black Desert Online Style of Enchantment enhancing
[23:26:48 INFO]: Website: https://github.com/25
[23:26:48 INFO]: Authors: HealPot, HealPot and lgou2w
```

### Error Log:
None

### Advice to fix
Add a interval before getting data from the server when joining the server.

**Comment by weihao** [comment]
Add a cooldown when switching servers? The problem could be the latency that writes to the database.

Even adding a repeatable task will sometimes cause data loss if there is a delay.

**Comment by Soldier233** [comment]
yes.
But I found plugin Mypet solved this problem by adding a delay in fetching data from db.

**Comment by Soldier233** [comment]
btw. Is there a api to get the level of player's weapon and armour.
I want to enhance the monster of the players nearby according to their levels.

**Comment by weihao** [comment]
> yes.
> But I found plugin Mypet solved this problem by adding a delay in fetching data from db.

What do you mean by that? Do you mean adding a delay when a player joins the server?

**Comment by Soldier233** [comment]
use runTaskLater(instance,20l) to get the data from mysql when joining thw server
