### ISSUE TITLE
如何通过Myticmobs掉落黑石等物品？

### ISSUE THREAD

**Issue by toponeme** [weihao/EnchantmentsEnhance#199]
如题

**Comment by weihao** [comment]
https://github.com/weihao/EnchantmentsEnhance/wiki/%E9%99%84%E9%AD%94%E5%BC%BA%E5%8C%96%E5%AE%8C%E6%95%B4%E6%96%87%E6%A1%A3#%E7%94%9F%E6%B4%BB%E5%A5%96%E5%8A%B1

**Comment by weihao** [comment]
你可以实体化黑石后，然后给予mm生成的怪物掉落。

**Comment by toponeme** [comment]
> 你可以实体化黑石后，然后给予mm生成的怪物掉落。

如何实体化黑石？

**Comment by weihao** [comment]
https://github.com/weihao/EnchantmentsEnhance/wiki/%E9%99%84%E9%AD%94%E5%BC%BA%E5%8C%96%E5%AE%8C%E6%95%B4%E6%96%87%E6%A1%A3#%E7%89%A9%E5%93%81%E5%8C%96
