### ISSUE TITLE
Bug touch

### ISSUE THREAD

**Issue by HiJackerRZ** [weihao/EnchantmentsEnhance#204]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
Yes
### What behaviour is observed:
What was the error?
Duplicate spawners
### Steps to reproduce:
How did you cause the issue?
Mine a spawner whit touch
### Plugin list:
This can be found by running `/pl`
NO
### Environment description
What server and version?
titan.army  | 1.15.2
### Enchantments Enhance build number:
This can be found by running `/enhance version`
Ask an admin for help whit this
### Error Log:
Link of the error log or stacktrace (if any, full log preferred)

**Comment by weihao** [comment]
```
disabledEnchantments:
  # Plugin will take control of the player's fly permissions.
  - Wings
  # Plugin will use the economic plugin.
  - Thief
  # Plugin will disable silk touch mining spawners from dropping a spawner.
  - Touch
```

**Comment by weihao** [comment]
Try add `Touch` to disabledEnchantments
