### ISSUE TITLE
Furnace BUG：black stone duplication   1.15.2   7.9.15

### ISSUE THREAD

**Issue by An-Shao** [weihao/EnchantmentsEnhance#214]
服务器核心 paper 1.15.2
插件版本  7.9.15

 bug : 熔炉内，烧制的成品栏格子满了之后，SHIFT+左键疯狂点击矿物的格子会出现刷黑石的情况，经过测试，除煤原矿外，其他矿物都有这种情况发生。
为了避免在服务器中其他插件的干扰，我在本地的端进行了测试，pl包括:vault 和插件本体7.9.15
bug内容如有描述不清，有视频已上传百度云，没法传附件
链接：https://pan.baidu.com/s/1qy91Ts-foSTZQHN6kYIrXQ 
提取码：s2no

希望尽快修复

**Comment by weihao** [comment]
感谢反馈，已修复

请下载最新版
