### ISSUE TITLE
Flying enchant disable flying in spectator mode

### ISSUE THREAD

**Issue by lapinizer** [weihao/EnchantmentsEnhance#217]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

v7.9.9

### What behaviour is observed:
What was the error?
When activating "Flying" enchant, disallow to fly in spectator mode.
- i set myself to Creative mode, then fly.
- While floating, i switch to spectator mode
- here i'm still flying... mayfly/fly values at 1b
- Once i move, or just turn the head around, i fall. mayfly/fly values are set to 0b
- i could remove the bug once i disable flying enchant and set "allow-flight" to true

### Steps to reproduce:
How did you cause the issue?
Enabling Flying enchant, plugin loaded, then switching to spectator mode.

### Plugin list:
This can be found by running `/pl`
Plugins (23): AdvancedRedstone, AutoCraft, ChestsPlusPlus, EnchantmentsEnhance, ItemInChatFree, KeepChunks, LevelledMobs, LoginSecurity*, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, MythicMobs, OnePlayerSleep, RecipeManager, RedstoneProximitySensor, SilkSpawners, SkQuery, Skript, VeryDangerousNether, XPHearts*

### Environment description
What server and version?
Paper on 1.15.2-R0.1-SNAPSHOT

### Enchantments Enhance build number:
This can be found by running `/enhance version`
v7.9.9

### Error Log:
Link of the error log or stacktrace (if any, full log preferred)

**Comment by weihao** [comment]
Thank you for reporting this bug!
