### ISSUE TITLE
Marketplace implementation.

### ISSUE THREAD

**Issue by weihao** [weihao/EnchantmentsEnhance#41]
```
itemId: 0
startingPrice: 100
buyPrice: 100%
sellPrice: 95%
buyIncreaseRatio: 5%
sellDecreaseRatio: 5%
minimumPrice: 10
maximumPrice: 10000
```
- A player buys 1 item0 for the price of 100$ from the marketplace.
- Price of item 0 increased to 105$ per item.
- A player sells 1 item0 for the price of 105$ from the marketplace and gained 99.75$.
- Price of item 0 decreased to 99.75$ per item.

**Comment by 25** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [拍卖场](https://trello.com/c/mGExKJMs/3-%E6%8B%8D%E5%8D%96%E5%9C%BA)

**Comment by weihao** [comment]
Not within the scope of this project.
